server:
  port: 8080

spring:
  application:
    name: clx-gateway
  profiles:
    active: dev

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: false
      config:
        server-addr: localhost:8848
        enabled: false

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: clx-auth
          uri: http://localhost:9100
          predicates:
            - Path=/auth/**
        - id: clx-user
          uri: http://localhost:9202
          predicates:
            - Path=/user/**
        - id: clx-post
          uri: http://localhost:9300
          predicates:
            - Path=/post/**,/category/**,/tag/**,/comment/**
        - id: clx-search
          uri: http://localhost:9400
          predicates:
            - Path=/search/**

logging:
  level:
    com.clx: debug
    org.springframework.cloud.gateway: info
